name: theory_of_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.4
  - catboost==1.2.7
  - jupyterlab>=4.0.11
  - matplotlib>=3.5.1
  - numpy>=1.26.4
  - pandas>=2.2.2
  - scikit-learn>=1.4.2
  - shap>=0.46.0